export default {
    // BackgroundImage: require('./BackgroundImage.png'),
    Logo: require('./logo.png'),
    Profile: require("./create-profile.png"),
    User: require("./user.png"),
    Post: require("./view.png"),
    Lock: require("./Lock.png"),
    Send: require("./send.png"),
    Sphere: require("./sphere.png"),
    Thumb: require("./thumb.png"),
    WelcomeBg: require("./welcomebg.png"),
    LoginBg: require("./loginBg.png"),
    LoginIcon: require("./loginIcon.png"),
    Img1: require("./img1.png"),
    Img2: require("./img2.png"),
    Img3: require("./img3.png"),
    Img4: require("./img4.png"),
    Img5: require("./img5.png"),
    BtnBg: require("./btnBg.png"),
    Union: require('./union.png'),
    Doc: require('./doc.png'),
    DocImg: require('./docImg.png')
}