export const usStates = [
  { id: "alabama", title: "Alabama" },
  { id: "alaska", title: "Alaska" },
  { id: "arizona", title: "Arizona" },
  { id: "arkansas", title: "Arkansas" },
  { id: "california", title: "California" },
  { id: "colorado", title: "Colorado" },
  { id: "connecticut", title: "Connecticut" },
  { id: "delaware", title: "Delaware" },
  { id: "florida", title: "Florida" },
  { id: "georgia", title: "Georgia" },
  { id: "hawaii", title: "Hawaii" },
  { id: "idaho", title: "Idaho" },
  { id: "illinois", title: "Illinois" },
  { id: "indiana", title: "Indiana" },
  { id: "iowa", title: "Iowa" },
  { id: "kansas", title: "Kansas" },
  { id: "kentucky", title: "Kentucky" },
  { id: "louisiana", title: "Louisiana" },
  { id: "maine", title: "Maine" },
  { id: "maryland", title: "Maryland" },
  { id: "massachusetts", title: "Massachusetts" },
  { id: "michigan", title: "Michigan" },
  { id: "minnesota", title: "Minnesota" },
  { id: "mississippi", title: "Mississippi" },
  { id: "missouri", title: "Missouri" },
  { id: "montana", title: "Montana" },
  { id: "nebraska", title: "Nebraska" },
  { id: "nevada", title: "Nevada" },
  { id: "new hampshire", title: "New Hampshire" },
  { id: "new jersey", title: "New Jersey" },
  { id: "new mexico", title: "New Mexico" },
  { id: "new york", title: "New York" },
  { id: "north carolina", title: "North Carolina" },
  { id: "north dakota", title: "North Dakota" },
  { id: "ohio", title: "Ohio" },
  { id: "oklahoma", title: "Oklahoma" },
  { id: "oregon", title: "Oregon" },
  { id: "pennsylvania", title: "Pennsylvania" },
  { id: "rhode island", title: "Rhode Island" },
  { id: "south carolina", title: "South Carolina" },
  { id: "south dakota", title: "South Dakota" },
  { id: "tennessee", title: "Tennessee" },
  { id: "texas", title: "Texas" },
  { id: "utah", title: "Utah" },
  { id: "vermont", title: "Vermont" },
  { id: "virginia", title: "Virginia" },
  { id: "washington", title: "Washington" },
  { id: "west virginia", title: "West Virginia" },
  { id: "wisconsin", title: "Wisconsin" },
  { id: "wyoming", title: "Wyoming" }
];